holaplex/helm-charts

- charts/hub-orgs/Chart.yaml
- charts/hub-orgs/templates/environment.yaml
- charts/hub-orgs/values.yaml
- Set KRATOS_BROKER environment on hub-orgs
> Set Environment for Kafka Brokers on Hub Orgs

- charts/hub-orgs/Chart.yaml
- charts/hub-orgs/templates/environment.yaml
- charts/hub-orgs/templates/secrets.yaml
- charts/hub-orgs/values.yaml
> Configure hub-orgs for svix

- charts/hub-gateway/Chart.yaml
- charts/hub-gateway/values.yaml
- Send `/organizations/new` to hub ui
> [Hub Gateway] Route organizations new route

- charts/hub-treasuries/Chart.yaml
- charts/hub-treasuries/templates/environment.yaml
- charts/hub-treasuries/templates/secrets.yaml
- charts/hub-treasuries/values.yaml
- Set kafka username and password on hub-treasuries
> [Hub Treasuries] Kafka username and password

- charts/hub-customers/.helmignore
- charts/hub-customers/Chart.yaml
- charts/hub-customers/templates/_helpers.tpl
- charts/hub-customers/templates/deployment.yaml
- charts/hub-customers/templates/environment.yaml
- charts/hub-customers/templates/hpa.yaml
- charts/hub-customers/templates/migrate.yaml
- charts/hub-customers/templates/secrets.yaml
- charts/hub-customers/templates/service.yaml
- charts/hub-customers/templates/serviceaccount.yaml
- charts/hub-customers/values.yaml
- Add helm chart for customers
> Hub Customers

- charts/hub-treasuries/Chart.yaml
- charts/hub-treasuries/templates/environment.yaml
- charts/hub-treasuries/values.yaml
- Able to set `FIREBLOCKS_SUPPORTED_ASSET_IDS`
> [Hub Treasuries] Fireblocks supported asset ids environment

- charts/hub-ui/Chart.yaml
- charts/hub-ui/templates/environment.yaml
- charts/hub-ui/templates/secrets.yaml
- charts/hub-ui/values.yaml
- Add secrets for setting nft storage auth token
-Set IPFS gateway through environment
> Setup Hub UI for NFT Storage

- charts/hub-credentials/Chart.yaml
- charts/hub-credentials/templates/environment.yaml
- charts/hub-credentials/templates/secrets.yaml
- charts/hub-credentials/values.yaml
- Add environment configuration for connecting to redpanda
> Allow hub-credentials to connect to redpanda

- charts/hub-gateway/Chart.yaml
- charts/hub-gateway/plugins/session.lua
let the redirect plugin manage above case
> remove status code from return when no session is found

- charts/hub-credits/Chart.yaml
- charts/hub-credits/templates/credit-sheet-cm.yaml
- charts/hub-credits/templates/deployment.yaml
- charts/hub-credits/templates/environment.yaml
- charts/hub-credits/values.yaml
- Setup reading the credit-sheet.toml from a config map
> [Hub Credits] Credit Sheet

- charts/hub-gateway/Chart.yaml
- charts/hub-gateway/values.yaml
- Revert back to webpack for the dev sever since nft.storage can't resolve
> [Hub Gateway] Webpack Dev Server

- charts/hub-gateway/Chart.yaml
- charts/hub-gateway/values.yaml
- Expose public routes for hub for terms of service and privacy policy
> Terms of service and privacy policy routes to gateway

- charts/hub-nfts/Chart.yaml
- charts/hub-nfts/templates/environment.yaml
- charts/hub-nfts/values.yaml
- charts/hub-orgs/Chart.yaml
- charts/hub-orgs/templates/environment.yaml
- charts/hub-orgs/values.yaml
- Add environment variable for ASSET_CDN to hub-orgs and hub-nfts
> ASSET_CDN for hub-nfts and hub-orgs

- charts/hub-ui/Chart.yaml
- charts/hub-ui/templates/environment.yaml
- charts/hub-ui/values.yaml
The request origin from the container is the kubernetes service.
Set the public fqdn through environment variable.
> Hub UI FQDN

- charts/hub-ui/Chart.yaml
- charts/hub-ui/templates/environment.yaml
- charts/hub-ui/values.yaml
Reverts holaplex/helm-charts#79
> Revert "Hub UI FQDN"

- charts/hub-treasuries/Chart.yaml
- charts/hub-treasuries/templates/deployment.yaml
- charts/hub-treasuries/templates/environment.yaml
- charts/hub-treasuries/values.yaml
- Update treasuries chart to land the credit sheet
> [Treasuries] Charge Credits for Wallet Creation

- charts/hub-credits/Chart.yaml
- charts/hub-credits/values.yaml
- charts/hub-gateway/Chart.yaml
- charts/hub-gateway/values.yaml
- charts/hub-treasuries/Chart.yaml
- Update gateway to route inbound webhook requests to credits.
- Refactor gateway routes
- Expose stripe credentials to hub-credits
> Credits Webhook for fulfilling credit purchases from Stripe

- charts/hub-credits/Chart.yaml
- charts/hub-credits/values.yaml
- Resolve issue with hub-nfts booting by adding action for retry drop
> Add action for retry drop

- charts/hub-nfts-solana/.helmignore
- charts/hub-nfts-solana/Chart.yaml
- charts/hub-nfts-solana/templates/_helpers.tpl
- charts/hub-nfts-solana/templates/deployment.yaml
- charts/hub-nfts-solana/templates/environment.yaml
- charts/hub-nfts-solana/templates/hpa.yaml
- charts/hub-nfts-solana/templates/migrate.yaml
- charts/hub-nfts-solana/templates/secrets.yaml
- charts/hub-nfts-solana/templates/serviceaccount.yaml
- charts/hub-nfts-solana/values.yaml
- charts/hub-nfts/Chart.yaml
- charts/hub-nfts/templates/deployment.yaml
- charts/hub-nfts/templates/environment.yaml
- charts/hub-nfts/values.yaml
- charts/hub-treasuries/templates/environment.yaml
- Add helm chart for hub-nfts-solana
- Adjust hub-treasuries and hub-nfts to support multi-chain where dedicate services per blockchain
> Hub NFTs Solana Chart and Refactor for Multichain

- charts/hub-credits/Chart.yaml
- charts/hub-credits/values.yaml
- Add default credit values for polygon for local development
> [Credits] Add stub credit values for polygon

- charts/hub-nfts-solana/Chart.yaml
- charts/hub-nfts-solana/templates/deployment.yaml
- charts/hub-nfts-solana/templates/indexer.yaml
- charts/hub-nfts-solana/templates/secrets.yaml
- charts/hub-nfts-solana/values.yaml
- Add deployment for running solana indexer in hub-nfts-solana chart
> Solana Indexer Deployment

- charts/hub-nfts-polygon/Chart.yaml
- charts/hub-nfts-polygon/templates/consumer.yaml
- charts/hub-nfts-polygon/templates/indexer.yaml
- charts/hub-nfts-polygon/templates/service.yaml
- charts/hub-nfts-polygon/values.yaml
- Run indexer in its own deployment
> Polygon deployment indexer

- charts/hub-nfts-solana/Chart.yaml
- charts/hub-nfts-solana/templates/environment.yaml
- charts/hub-nfts-solana/templates/secrets.yaml
- charts/hub-nfts-solana/values.yaml
- Add environment variables for doing compression
> [NFTs Solana] Environment Variables for Compression

- charts/hub-ui/Chart.yaml
- charts/hub-ui/templates/secrets.yaml
- charts/hub-ui/values.yaml
Add key and proof secret entries for web3 up to hub-ui.
> [HUB UI] Secrets for Web3 up

- charts/hub-ui/Chart.yaml
- charts/hub-ui/templates/environment.yaml
- charts/hub-ui/templates/secrets.yaml
- charts/hub-ui/values.yaml
- Remove config related to nft.storage
> Remove Uploads

- charts/hub-uploads/Chart.yaml
- charts/hub-uploads/templates/environment.yaml
- charts/hub-uploads/templates/secrets.yaml
- charts/hub-uploads/values.yaml
- Hub Uploads switch to bundlr. Setup environment changes to the service.
> [Hub Uploads] Switch to Bundlr
